name: inventario_ti_web
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Iconos y comunicación con API
  dio: ^5.4.0
  lucide_icons: ^0.257.0
  http: ^0.13.6
  cupertino_icons: ^1.0.8
  intl: ^0.18.1
  fl_chart: ^0.64.0
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
